name: 'Terraform Deployment'
run-name: ${{ github.actor }} is deploying...

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform apply or destroy?'
        required: true
        default: 'apply'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRECT_KEY }}
          aws-region: ap-southeast-2 

      - name: HashiCorp-Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.3

      - name: zip files for lambda function
        run: |
          zip -j lambda_code_s3tosagemaker.zip ./dataserving/de-ers_s3tosagemaker.py
          zip -j lambda_function_get_recommendation.zip ./dataserving/de-ers_API.py
          mv lambda_code_s3tosagemaker.zip terraform/
          mv lambda_function_get_recommendation.zip terraform/

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init
        
      - name: Terraform fmt
        working-directory: ./terraform
        run: terraform fmt

      - name: Terraform plan
        working-directory: ./terraform
        run: terraform plan

      - name: Terraform Apply or Destroy
        working-directory: ./terraform
        run: |
          if [ "${{ github.event.inputs.action }}" = "apply" ]; then
            terraform apply -auto-approve
            aws s3 cp ./terraform.tfstate s3://de-ers.imba-bucket/terraform-statefile/terraform.tfstate
          elif [ "${{ github.event.inputs.action }}" = "destroy" ]; then
            aws s3 cp s3://de-ers.imba-bucket/terraform-statefile/terraform.tfstate .
            terraform destroy -auto-approve
          else
            echo "Invalid action specified"
            exit 1
          fi
